### ISSUE TITLE
Gems not registering

### ISSUE THREAD

**Issue by Chorigh** [Daripher/Passive-Skill-Tree#151] opened 2024-01-12 00:02 UTC
Playing on a multiplayer server and the gems have no texture (purple and black checkered box). Instead of the kind of gem it just says item.skilltree.gem.skilltree.none
![2024-01-11_17 56 04](https://github.com/Daripher/Passive-Skill-Tree/assets/156382410/efae082b-7830-4928-a04f-af1864ab6f1a)

**Comment by maiteko** [comment] 2024-01-13 04:02
Seeing the same problem. Currently on the 1.19.2 version.

I see compatibility was added for the apotheosis system recently, might have something to do with that.

**Comment by Ke-Hab** [comment] 2024-01-14 10:05
I think that I have found a solution to this problem. You just need to go into a single player game and log back into the server.

**Comment by Daripher** [comment] 2024-01-14 19:31
Duplicate of #148

**Closed as completed by Daripher** 2024-01-14 19:31 UTC
Labels: duplicate
