### ISSUE TITLE
Server Gemstone missing texture

### ISSUE THREAD

**Issue by Mirerew** [Daripher/Passive-Skill-Tree#150] opened 2024-01-11 14:36 UTC
Playing on server with my friend. He sees the gem textures (hes hosting on LAN) and i just see missing texture with no item destcription.

We are playing on version 1.20.1 and mod version : 1.20.1-Beta-0.6.5.-all.jar

**Comment by Daripher** [comment] 2024-01-11 19:11
Duplicate of #148

**Closed as completed by Daripher** 2024-01-11 19:11 UTC
Labels: bug, duplicate
