### ISSUE TITLE
Crash with From The Shadow Mod

### ISSUE THREAD

**Issue by 5stigma** [Daripher/Passive-Skill-Tree#116] opened 2023-12-18 19:58 UTC
Cleric attack crash
[crash-2023-12-18_03.05.42-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13708031/crash-2023-12-18_03.05.42-server.txt)

**Comment by Daripher** [comment] 2023-12-18 20:10
Report that to the From The Shadow mod's author and tell them that they shouldn't return `null` in the `AbstractArrow#getPickupItem()`.
I will also add a null check in my mod to prevent such errors in the future.

**Comment by Daripher** [comment] 2023-12-18 20:12
Duplicate of #101

**Closed as completed by Daripher** 2023-12-18 20:12 UTC
Labels: bug, incompatibility

**Comment by 5stigma** [comment] 2023-12-19 00:33
The version PassiveSkillTree-1.19.2-BETA-0.5.10b is Ok
